---
title: Beyonce-Words
author: Robert W. Walker
date: '2020-10-19'
slug: beyonce-words
categories:
  - tidyTuesday
  - dataviz
tags:
  - tidyTuesday
subtitle: ''
summary: ''
authors: []
lastmod: '2020-10-19T02:11:17-07:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidytext)
library(here)
```

## tidyTuesday `beyonce_lyrics`

Load the data.

```{r}
beyonce_lyrics <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-29/beyonce_lyrics.csv')
str(beyonce_lyrics)
```

## Beyonce's Favorite Lyric Words

```{r}
beyonce_lyrics %>% 
  unnest_tokens(word, line) %>%   # Parse the lyric lines to tidy: one word per row.
  anti_join(., stop_words) %>%    # Remove the stop words
  group_by(word) %>%              # Group them by word
  summarise(Count = n()) %>%      # How common is the word?
  top_n(25) %>%                   # Keep the top 25
  ggplot() + 
  aes(x=fct_reorder(word, Count), y=Count) + 
  geom_col() + 
  coord_flip() + 
  labs(x="Word", title="Beyonce's Top Words in Lyrics")
```

## Beyonce's Cloud

```{r BC1}
library(wordcloud2)
beyonce_lyrics %>% 
  unnest_tokens(word, line) %>%   # Parse the lyric lines to tidy: one word per row.
  anti_join(., stop_words) %>%    # Remove the stop words
  group_by(word) %>%              # Group them by word
  summarise(Count = n()) %>%      # How common is the word?
  wordcloud2::wordcloud2(size = 0.7, shuffle = TRUE) -> WC111
# htmlwidgets::saveWidget(widgetframe::frameWidget(WC111), file='widgets/wcbey.html')
# MyWC
# widgetframe::frameWidget(WC111)
WC111
```

```{r BC2, eval=FALSE}
library(wordcloud2)
MyDat <- beyonce_lyrics %>% 
  unnest_tokens(word, line) %>%   # Parse the lyric lines to tidy: one word per row.
  anti_join(., stop_words) %>%    # Remove the stop words
  group_by(word) %>%              # Group them by word
  summarise(freq = n()) %>%      # How common is the word?
  arrange(desc(freq))
MyWC <- wordcloud2::letterCloud(MyDat, word="Most Popular \n Words in \n Beyonce \n Lyrics", wordSize = 1.75, backgroundColor="lightblue", color='random-dark', size=0.8)
htmlwidgets::saveWidget(widgetframe::frameWidget(MyWC), file='widgets/beyonce.html')
# MyWC
# widgetframe::frameWidget(MyWC)
```

Something about this does not seem to work now.

