---
title: "tidyQuant"
author: "Robert W. Walker"
date: "3/11/2020"
output: 
   html_document:
     self_contained: true
     code_folding: show
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## tidyquant

Automates a lot of equity research and calculation using *tidy* concepts.

```{r cars, message=FALSE}
library(tidyquant)
ticker <- "GS"
GS <- ticker %>% tq_get(from="2017/02/01", to="2020/03/01")
GS.Returns <- GS %>% tq_transmute(close, periodReturn, period="monthly")
GSPC <- "^GSPC" %>% tq_get(from="2017/02/01", to="2020/03/01")
GSPC.Returns <- GSPC %>% tq_transmute(close, periodReturn, period="monthly")
My.data <- left_join(GSPC.Returns,GS.Returns,by="date")
summary(lm(monthly.returns.y~monthly.returns.x, data=My.data))
```

## A Plot

```{r pressure, echo=FALSE}
plot(x=My.data$date, My.data$monthly.returns.y, type="l", xlab="Date", ylab="Monthly Returns")
lines(x=My.data$date, My.data$monthly.returns.x, col="red")
legend("top", legend=c("GSPC",ticker), col=c("black","red"), lty=c(1,1))
```
