library(ggrepel)
library(haven)
library(tidyverse)
library(osmdata)
library(sf)
library(ggmap)
library(emojifont)
library(kableExtra)
library(OpenStreetMap)
library(lubridate)
library(utf8)
library(emoGG)
library(ggthemes)
library(janitor)
library(ggridges)
library(viridis)
library(ggrepel)
library(ggmosaic)
library(gridExtra)
library(here)
library(wordcloud2)
library(gganimate)
library(flipbookr)
Archigos <- read_dta(url("http://www.rochester.edu/college/faculty/hgoemans/Archigos_4.1_stata14.dta"))
Archigos <- Archigos %>% mutate(leader = utf8_encode(leader))
